name: Release

on:
  release:
    types: [published]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy_to_amplify:
    name: Request Amplify Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send request to Amplify deploy webhook
        run: curl -X POST -d {} -H "Content-Type:application/json" ${{ secrets.AMPLIFY_DEPLOY_WEBHOOK }}
